export const sampleChats = [
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John",
    _id: "1",
    groupChat: true,
    members: [1, 2, 3, 4, 5],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Jane",
    _id: "2",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Alice",
    _id: "3",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Bob",
    _id: "4",
    groupChat: true,
    members: [1, 2, 3, 4],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Charlie",
    _id: "5",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Dave",
    _id: "6",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Eve",
    _id: "7",
    groupChat: true,
    members: [1, 2, 3],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Frank",
    _id: "8",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Grace",
    _id: "9",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Heidi",
    _id: "10",
    groupChat: true,
    members: [1, 2, 3, 4, 5],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "John",
    _id: "11",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Jane",
    _id: "12",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Alice",
    _id: "13",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Bob",
    _id: "14",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Charlie",
    _id: "15",
    groupChat: true,
    members: [1, 2, 3, 4, 5],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Dave",
    _id: "16",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Eve",
    _id: "17",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Frank",
    _id: "18",
    groupChat: false,
    members: [1, 2],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Grace",
    _id: "19",
    groupChat: true,
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    Avatar: "https://www.w3schools.com/howto/img_avatar.png",
    name: "Heidi",
    _id: "20",
    groupChat: false,
    members: [1, 2],
  },
];
